(evil-mode 1)
(evil-leader/set-key "w" 'evil-window-next)
(evil-leader/set-key "d" 'evil-delete-buffer)
(evil-leader/set-key "o" 'delete-other-windows)
(define-key evil-normal-state-map "|" 'evil-window-vsplit)
