(eval-after-load "undo-tree" '(diminish 'undo-tree-mode))
(eval-after-load "helm" '(diminish 'helm-mode))
(eval-after-load "git-gutter" '(diminish 'git-gutter-mode))
(eval-after-load "anzu" '(diminish 'anzu-mode))
(eval-after-load "auto-complete" '(diminish 'auto-complete-mode))
