(setq sml/theme 'respectful)
(require 'smart-mode-line)
(sml/setup)
(add-to-list 'sml/hidden-modes " Helm")
(add-to-list 'sml/hidden-modes " Undo-Tree")
(add-to-list 'sml/hidden-modes " Anzu")
(add-to-list 'sml/hidden-modes " AC")
