(setq helm-c-locate-command
      (case system-type
	('gnu/linux "locate -i -r %s")
	('berkeley-unix "locate -i %s")
	('windows-nt "es %s")
	('darwin "mdfind -name %s %s")
	(t "locate %s"))
      )
(helm-mode 1)
(global-set-key (kbd "C-x C-m") 'helm-M-x)
(global-set-key (kbd "C-c C-m") 'helm-M-x)
(define-key global-map [remap find-file] 'helm-find-files)
(define-key global-map [remap occur] 'helm-occur)
(define-key global-map [remap list-buffers] 'helm-buffers-list)
(define-key global-map [remap yank-pop] 'helm-show-kill-ring)
(define-key isearch-mode-map [remap isearch-occur] 'helm-occur-from-isearch)
